#!/bin/sh
#
# Script name: bb_IDP_SWI_T2star
#
# Description: Script to generate the IDPs related to swMRI.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

cd $direc

baseT1="T1"
#if [ -d T1/unusable ] ; then
#    baseT1="T1/unusable"
#fi

baseSWI="SWI"
#if [ -d $baseSWI/unusable ] ; then
#    baseSWI="$baseSWI/unusable"
#fi

#Setting the string of NaN in case there is a problem.
numVars="14"
result="";
for i in $(seq 1 $numVars) ; do
    result="NaN $result" ;
done

vals=()
if [ -f $baseSWI/T2star_to_T1.nii.gz ] ; then
 if [ -f $baseT1/T1_first/T1_first_all_fast_firstseg.nii.gz ] ; then
  for int_val in 10 49 11 50 12 51 13 52 17 53 18 54 26 58; do
   fslmaths $baseT1/T1_first/T1_first_all_fast_firstseg -thr $int_val -uthr $int_val  -bin  temp;
   val_ind=`fslstats -K temp  $baseSWI/T2star_to_T1 -p 50`;
   vals+=( "$val_ind" )
  done
  result=`echo ${vals[@]}`
 fi
fi
imrm temp
mkdir -p IDP_files

echo $result > IDP_files/$scriptName.txt
echo ${vals[@]}

cd $origDir
