#!/bin/sh
#
# Script name: bb_NODDI_cudimot
#
# Description: Script to generate the NODDI_cudimot outputs for dMRI
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

logDir=$PWD/$1/"/logs/"
logFile=$logDir"bb_NODDI_cuDIMOT__"$1"__"$$".log"

exec 3>&1 4>&2 1> $logFile 2>&1

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header

execPath=`dirname $0`

cd $1

SUBDIR=`pwd`
SUB=`basename $SUBDIR`

#Making directory structure
mkdir -p $SUBDIR/dMRI/bb_NODDI_cuDIMOT

if [ -d $SUBDIR/dMRI/dMRI ] ; then


    #Populating the pre cudimot directory with the necessary files required for it to run
    cp $SUBDIR/dMRI/dMRI/data_ud.nii.gz $SUBDIR/dMRI/bb_NODDI_cuDIMOT/data.nii.gz
    cp $SUBDIR/dMRI/dMRI/nodif_brain_mask.nii.gz $SUBDIR/dMRI/bb_NODDI_cuDIMOT/nodif_brain_mask.nii.gz
    #cp -r $SUBDIR/dMRI/dMRI.bedpostX/* $SUBDIR/dMRI/bb_NODDI_cuDIMOT

    # Line which runs cuDIMOT
    $BB_BIN_DIR/bb_diffusion_pipeline/bb_NODDI_cuDIMOT/Pipeline_NODDI_Watson.sh $SUBDIR/dMRI/bb_NODDI_cuDIMOT

    job_bb_NODDI=`${FSLDIR}/bin/fsl_sub -T 60  -N "bb_bb_NODDI_"{$1}   -l  $logDir $BB_BIN_DIR/bb_diffusion_pipeline/bb_NODDI_cuDIMOT/Pipeline_NODDI_Watson.sh $SUBDIR/dMRI/bb_NODDI_cuDIMOT`
    job_post_NODDI=`${FSLDIR}/bin/fsl_sub -T 15 -N "bb_post_NODDI_cuDIMOT_"{$1} -j $job_bb_NODDI -l $logDir $BB_BIN_DIR/bb_diffusion_pipeline/bb_NODDI_cuDIMOT/bb_post_NODDI`
fi;

cd $ANALROOT

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer
