#!/bin/sh

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header



direc=$PWD/$1
mkdir -p $direc/MIST/data

#prepare data for MIST

# Prepare data for eddy, dtifit and bedpostx.
ln -s $direc/T1/T1.nii.gz $direc/MIST/data/T1.nii.gz 
#cp -s $direc/T2_FLAIR/T2_FLAIR.nii.gz $direc/MIST/data/T2_FLAIR_native_T2.nii.gz

flirt -in $direc/T2_FLAIR/T2_FLAIR.nii.gz -ref $direc/MIST/data/T1.nii.gz  -out $direc/MIST/data/T2_FLAIR.nii.gz

if [ $2 = True ]
then
    ln -s $direc/dMRI/TBSS/FA/dti_FA.nii.gz $direc/MIST/data/dti_FA.nii.gz
    flirt -dof 6 -cost bbr -wmseg $direc/T1/T1_fast/T1_brain_WM_mask.nii.gz -bbrtype global_abs -in $direc/MIST/data/dti_FA.nii.gz -ref $direc/T1/T1_brain.nii.gz -out $direc/MIST/data/FA_to_T1 -omat $direc/MIST/data/FA_to_T1_mat
    #applywarp -i $direc/dMRI/TBSS/FA/dti_FA_to_MNI -o $direc/MIST/FA_to_T1 -r $direc/T1/T1 -w ../../../T1/transforms/T1_to_MNI_warp_coef_inv.nii.gz 
fi

#Creating mist subjects file
echo "$direc/MIST/data" > $direc/MIST/mist_subjects 
echo "$direc/MIST/data" > $direc/MIST/mist_training_subjects 

#Creating mist filenames file 
echo ""T1","T1","T1",1.0" > $direc/MIST/mist_filenames
echo ""T2_FLAIR","T2","T2_FLAIR",1.5" >> $direc/MIST/mist_filenames 

if [ $2 = True ]
then
    echo ""FA","FA","FA_to_T1",1.0" >> $direc/MIST/mist_filenames
fi
here=`pwd`
cd $direc/MIST
mist_1_train
mist_2_fit
cd $here

